# Toolchain config for Android NDK.
# This is expected to be used with a standalone Android toolchain (see
# docs/STANDALONE-TOOLCHAIN.html in the NDK on how to get one).
#
# Usage:
# mkdir build; cd build
# cmake ..; make
# mkdir android; cd android
# cmake -DLLVM_ANDROID_TOOLCHAIN_DIR=/path/to/android/ndk \
#   -DCMAKE_TOOLCHAIN_FILE=../../cmake/platforms/Android.cmake ../..
# make <target>
find_program(CCACHE_FOUND ccache)
if(CCACHE_FOUND)
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
    set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
endif(CCACHE_FOUND)

# common settings
SET(CMAKE_SYSTEM_NAME Android)
SET(CMAKE_SYSTEM_PROCESSOR $ENV{TARGET})
SET(CMAKE_HOST_NAME $ENV{HOST})
SET(CMAKE_TARGET_NAME $ENV{TARGET})
SET(CMAKE_OSX_SYSROOT $ENV{TOOLCHAIN_PATH}/sysroot)

SET(CMAKE_BUILD_ENGINE $ENV{BUILD_ENGINE})
# sysroot and toolchain path settings
SET(CMAKE_CROSSCOMPILING ON CACHE BOOL "Cross-compiling" FORCE)
SET(CMAKE_ANDROID_STANDALONE_TOOLCHAIN $ENV{TOOLCHAIN_PATH})
SET(CMAKE_TOOLCHAIN_PATH $ENV{TOOLCHAIN_PATH})
SET(CMAKE_FIND_ROOT_PATH ${CMAKE_TOOLCHAIN_PATH})
SET(CMAKE_ANDROID_SYSROOT $ENV{TOOLCHAIN_PATH}/sysroot)
SET(CMAKE_SYSROOT, ${CMAKE_ANDROID_SYSROOT})

# common cxx include path settings
SET(CMAKE_ANDROID_STL_INCLUDE $ENV{TOOLCHAIN_PATH}/include/c++/4.9.x/)
SET(CMAKE_SHARED_LIBRARY_SONAME_CXX_FLAG "")
SET(CMAKE_READELF ${CMAKE_TOOLCHAIN_PATH}/bin/$ENV{GCC_TOOL_PRENAME}-readelf)

string(COMPARE EQUAL "$ENV{BUILD_ENGINE}" "gcc" gcc_compile)
if(gcc_compile)
# remove -install-name flag
#SET(CMAKE_SHARED_LIBRARY_SONAME_CXX_FLAG "")

SET(CMAKE_C_COMPILER ${CMAKE_TOOLCHAIN_PATH}/bin/$ENV{GCC_TOOL_PRENAME}-gcc)
SET(CMAKE_CXX_COMPILER ${CMAKE_TOOLCHAIN_PATH}/bin/$ENV{GCC_TOOL_PRENAME}-g++)
SET(CMAKE_AR ${CMAKE_TOOLCHAIN_PATH}/bin/$ENV{GCC_TOOL_PRENAME}-ar)
SET(CMAKE_STRIP ${CMAKE_TOOLCHAIN_PATH}/bin/$ENV{GCC_TOOL_PRENAME}-strip)
SET(CMAKE_RANLIB ${CMAKE_TOOLCHAIN_PATH}/bin/$ENV{GCC_TOOL_PRENAME}-ranlib)
SET(CMAKE_GCC_FLAGS $ENV{GCC_COMPILER_FLAGS})
else()
SET(CMAKE_BINARY_PATH $ENV{BINARY_PATH})
SET(CMAKE_GCC_PATH $ENV{GCC_PATH})
SET(CMAKE_TARGET_ABI_NAME $ENV{TARGET_ABI})
SET(CMAKE_CLANG_CFLAGS $ENV{CLANG_CFLAGS})
SET(CMAKE_TARGET_WORD_BITS $ENV{TARGET_WORD_BITS})
SET(CMAKE_C_COMPILER ${CMAKE_TOOLCHAIN_PATH}/bin/clang)
SET(CMAKE_CXX_COMPILER ${CMAKE_TOOLCHAIN_PATH}/bin/clang++)
SET(CMAKE_AR ${CMAKE_BINARY_PATH}/ar)
SET(CMAKE_RANLIB ${CMAKE_BINARY_PATH}/ranlib)
SET(CMAKE_STRIP ${CMAKE_BINARY_PATH}/strip)
endif()

set( CMAKE_SKIP_RPATH TRUE CACHE BOOL "If set, runtime paths are not added when using shared libraries." )
SET(ANDROID "1" CACHE STRING "ANDROID" FORCE)

if(gcc_compile)
SET(ANDROID_COMMON_FLAGS "--sysroot=${CMAKE_ANDROID_SYSROOT} -isystem ${CMAKE_ANDROID_STL_INCLUDE} ${CMAKE_GCC_FLAGS} -ffunction-sections -fdata-sections -Os")
else()
SET(ANDROID_COMMON_FLAGS "${CMAKE_CLANG_CFLAGS} --sysroot=${CMAKE_ANDROID_SYSROOT} -isystem ${CMAKE_ANDROID_STL_INCLUDE} -B${CMAKE_BINARY_PATH} -ffunction-sections -fdata-sections")
endif()
SET(CMAKE_C_FLAGS "${ANDROID_COMMON_FLAGS}" CACHE STRING "toolchain_cflags" FORCE)
SET(CMAKE_CXX_FLAGS "${ANDROID_COMMON_FLAGS} -std=gnu++1y" CACHE STRING "toolchain_cxxflags" FORCE)
SET(CMAKE_ASM_FLAGS "${ANDROID_COMMON_FLAGS}" CACHE STRING "toolchain_asmflags" FORCE)
SET(CMAKE_EXE_LINKER_FLAGS "$ENV{LIBCXX_LINK_TYPE} -pie" CACHE STRING "toolchain_exelinkflags" FORCE)
SET(CMAKE_SHARED_LINKER_FLAGS "$ENV{LIBCXX_LINK_TYPE} -Wl,--gc-sections -Wl,--build-id=sha1" CACHE STRING "toolchain_exelinkflags" FORCE)
SET(CMAKE_SHARED_LIBRARY_CREATE_CXX_FLAGS "-shared")
SET(CMAKE_SHARED_LIBRARY_PREFIX "lib")
SET(CMAKE_SHARED_LIBRARY_SUFFIX ".so")

if(gcc_compile)
#FIXME
link_libraries($ENV{DEFAULT_LIBRARY})
else()
link_libraries($ENV{DEFAULT_LIBRARY})
link_directories($ENV{SYS_LIBRARY_PATH})
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

if(gcc_compile)
SET(CMAKE_TARGET_WORD_BITS 32)
endif()

set(PORT JSCOnly)
set(WTF_CPU_$ENV{WTF_CPU} 1)
set(JavaScriptCore_LIBRARY_TYPE STATIC)
