/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_taobao_weex_bridge_WXBridge */

#ifndef _Included_com_taobao_weex_bridge_WXBridge
#define _Included_com_taobao_weex_bridge_WXBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_taobao_weex_bridge_WXBridge
 * Method:    initFramework
 * Signature: (Ljava/lang/String;Lcom/taobao/weex/bridge/WXParams;)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_weex_bridge_WXBridge_initFramework
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_taobao_weex_bridge_WXBridge
 * Method:    execJS
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Lcom/taobao/weex/bridge/WXJSObject;)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_weex_bridge_WXBridge_execJS
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
